### ISSUE TITLE
Improved communication with the backend so it isn't checked for updates unnecessarily 

### ISSUE THREAD

**Issue by portaljumper007** [PirateGame/Pirate-Game-Frontend#27]
for checking the player list
could you open a http request with like an hour timeout or something
then the backend can just respond when the player list changes
rather than every few seconds
and when the backend responds with a new playerlist, the frontend would open a new http request ready for it to change again

**Comment by Alex40144** [comment]
flask sockets.

**Comment by Alex40144** [comment]
#80 should fix this

**Comment by portaljumper007** [comment]
I'll reintroduce this as a new issue: "Flask sockets."
