### ISSUE TITLE
TurnNum % 2 = 0 or 1 and this should correspond to alternating event colours per turn.

### ISSUE THREAD

**Issue by portaljumper007** [PirateGame/Pirate-Game-Frontend#32]

**Comment by Alex40144** [comment]
each turn a different colour or a different colour for each event?

**Comment by portaljumper007** [comment]
Alternating colours for events based on turn. Eg: turn 1 events are dark grey, turn 2 events are light grey, turn 3 events are dark grey... so on.

**Comment by Alex40144** [comment]
not tested, but implemented. reopen if issue
