### ISSUE TITLE
Add username to game page.

### ISSUE THREAD

**Issue by portaljumper007** [PirateGame/Pirate-Game-Frontend#46]

**Comment by Alex40144** [comment]
more details please

**Comment by portaljumper007** [comment]
> more details please

Where it says the amount of cash and bank balance in the top right, it would be very helpful to say the turn number (eg 30/50) and username.

**Comment by Alex40144** [comment]
a hover for game info kind of thing?

**Comment by portaljumper007** [comment]
I think it would be good to show the username in the top right at all times or something like that. then turn number should be above the stats with the game name.

**Comment by Alex40144** [comment]
ok, we might need to make the text smaller then.

**Comment by portaljumper007** [comment]
> ok, we might need to make the text smaller then.

agreed. or... display the game name at the top in the middle with the turn number.

**Comment by Alex40144** [comment]
done
