### ISSUE TITLE
Game board page with drag and drop

### ISSUE THREAD

**Issue by portaljumper007** [PirateGame/Pirate-Game-Frontend#6]

**Comment by portaljumper007** [comment]
https://vuejsexamples.com/tag/drag/
http://dsmorse.github.io/gridster.js/
https://gridstackjs.com/

**Comment by portaljumper007** [comment]
@Alex40144 Now this issue just needs to build boards from serialised responses from the backend, and also freeze the board when the game starts.

**Comment by Alex40144** [comment]
done
